title: Dr Elliott Wise
theme: jekyll-theme-minimal
description: |
  I'm a London-based data engineering consultant, currently working for Gutteridge, Haskins & Davey
  (GHD) to improve the UK's national infrastructure. I'm passionate about exploring the frontiers
  of mathematics, modelling, and simulation, and proud of my history tackling  difficult challenges
  in science and engineering.
