title: Elliott Wise, PhD
theme: jekyll-theme-minimal
description: |
  I'm a London-based data engineering consultant, currently working for Gutteridge, Haskins & Davey
  (GHD) on engineering infrastructure projects. I'm passionate about exploring the frontiers of
  mathematics, modelling, and simulation, and proud of my history tackling difficult challenges in
  science and engineering.

  <div>
    <a href="https://scholar.google.co.uk/citations?user=5LE79rcAAAAJ&hl=en">
      View My Google Scholar Profile
    </a>
  </div>
