title: Elliott Wise, PhD
theme: jekyll-theme-minimal
description: |
  Elliott is a data science consultant - based in London and currently working for Gutteridge,
  Haskins & Davey (GHD) on engineering infrastructure projects. He's passionate about exploring the
  frontiers of mathematics, modelling, and simulation, and proud of his history tackling difficult
  challenges in science and engineering.
